### ISSUE TITLE
Bom Review

### ISSUE THREAD

**Issue by timChase98** [mbisbano1/ECE388_CatchTheLightV2#1]
- [x] Q-Touch button shouldn't be on the BOM
- [ ] battery holder should have the alt supplier colums filled out.  

Good work, please fix these things but I'll put you down as passed.

**Comment by mbisbano1** [comment]
For the price of the battery holder, I wasn't able to find it, and it isn't available on the link to it.
I have included the link to the battery holder on the BOM, but left the price blank.

I also removed the Q-touch button from the BOM as you recommended. 

Please let me know if anything else should be changed!
