### ISSUE TITLE
Board Submission

### ISSUE THREAD

**Issue by timChase98** [mbisbano1/ECE388_CatchTheLightV2#3]
- [x] Review the submission guidelines [HERE](https://github.com/timChase98/388Example)
- [x] Silkscreen labels must include
  - [x] Your Name
  - [x] Project Name
  - [x] Date
  - [x] Version/Rev
  - [x] Github Link
- [x] Check stock sheet for correct footprints for 
  - [x] Power Switch 
  - [x] Battery Holder
- [x] Placement of fiducials should be 
  - [x] FID1 lower left 
  - [x] FID2 upper left
  - [x] FID3 lower right
- [x] Looks like the silkscreen for the battery holder goes over the pads.  I would also add thermal relief to the center pad-gnd plane

These are initial comments meant to guide you though the layout process.  I will not look at your board again until your schematic passes review.  This is to reduce the workload on you by limiting the number of times you need to relayout your board due to schematic errors.  

Please address these issues and push your changes. Then create a new release, increment the tag and close this issue. I will review the changes and mark this as complete or reopen the issue with additional feedback.

**Comment by mbisbano1** [comment]
Are you able to specify what about my submission went against the submission guidelines? I thought I followed them quite well.

**Comment by timChase98** [comment]
Sorry you can ignore that.  Its from the template I used for everyone and I forgot to take it out for you

**Comment by mbisbano1** [comment]
@timChase98 when/if you get a chance could you look at the footprint I made for the switch? Low priority as I have the bypass solder junction there as you recommended.

**Comment by timChase98** [comment]
That looks correct to me.

**Comment by mbisbano1** [comment]
@timChase98 Yes, it was in the Gerber files. I was just concerned about the drills required.

**Comment by timChase98** [comment]
Ya it looks good as far as I can tell

**Comment by mbisbano1** [comment]
Okay, thank you.

**Comment by timChase98** [comment]
You have a couple of spots where the silkscreen overlaps the pads The text SJ2 and your + and - symbols.  Everything else looks good.

**Comment by mbisbano1** [comment]
Okay, I'll fix that quick. Thank you

**Comment by timChase98** [comment]
Looks good.  Move onto layout

**Comment by timChase98** [comment]
wrong tab ignore that

**Comment by mbisbano1** [comment]
Okay, I'll fix that quick. Thank you

**Comment by mbisbano1** [comment]
Issues fixed, and new Gerber Submission Release created.

**Comment by timChase98** [comment]
Still an issue for T1 and SJ2 should be next to the jumper not the test points

**Comment by mbisbano1** [comment]
Whoops. Thanks. I looked over every pad this time, should be good.

**Comment by timChase98** [comment]
This passes, good job

**Comment by mbisbano1** [comment]
Awesome, thank you

**Comment by timChase98** [comment]
Your board was sent to fab
